### ISSUE TITLE
Server crash error

### ISSUE THREAD

**Issue by jamesrichard91** [blackducksoftware/ducky-mod#7]
Error reported by legendaryjareon on the curseforge page

The forge version I use is 28.1.20.

 This is what I get:

Description: Exception in server tick loop
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ Ducky Mod (duckymod) encountered an error during the load_registries event phase§7net/minecraft/client/renderer/entity/EntityRenderer] at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {} at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:964) ~[?:?] {} at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {} at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Unknown Source) [?:1.8.0_212] {}

**Comment by jamesrichard91** [comment]
This should be resolved in version [0.4.1 ](https://github.com/blackducksoftware/ducky-mod/releases/tag/0.4.1).
